steps:
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/peppy-house-263912/monolognator', '.']
  - id: push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/peppy-house-263912/monolognator']
    waitFor:
    - build
  - id: delete
    name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/my-deployment', 'my-container=gcr.io/my-project/my-image']
  - id: apply
    name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/my-deployment', 'my-container=gcr.io/my-project/my-image']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'