apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: monolognator
  name: monolognator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: '6060'
        prometheus.io/scrape: 'true'
      labels:
        app: monolognator
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: config
          configMap:
            name: config
      containers:
      - image: registry.hub.docker.com/jambock/monolognator
        imagePullPolicy: Always
        name: monolognator
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - mountPath: /config
            name: config
        env:
          - name: telegram_token
            valueFrom:
              secretKeyRef:
                key: token
                name: telegram-token
          - name: giphy_token
            valueFrom:
              secretKeyRef:
                key: token
                name: giphy-token
          - name: darksky_token
            valueFrom:
              secretKeyRef:
                key: token
                name: darksky-token
          - name: tenor_token
            valueFrom:
              secretKeyRef:
                key: token
                name: tenor-token
          - name: untappd_client_id
            valueFrom:
              secretKeyRef:
                key: client-id
                name: untappd
          - name: untappd_client_secret
            valueFrom:
              secretKeyRef:
                key: client-secret
                name: untappd
          - name: CN
            value: monolognator.brunix.net
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
      restartPolicy: Always
      serviceAccountName: monolognator
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
imagePullSecrets:
  - name: docker
kind: ServiceAccount
metadata:
  labels:
    name: monolognator
  name: monolognator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monolognator
  name: monolognator
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: monolognator
  sessionAffinity: None
  type: NodePort

