apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {
      access_log /dev/stdout;
      server {
          listen       80;
          server_name  _;

          location /healthz {
            return 200 "What's up?\n";
          }

          location / {
            proxy_pass http://localhost:8080/;
            proxy_http_version 1.1;
          }
      }
    }
---
